---
commitizen:
  change_type_map:
    feat: Features
    fix: Bug fixes
  name: cz_conventional_commits
  tag_format: $version
  update_changelog_on_bump: true
  version_provider: commitizen-ruby
  version_scheme: semver
